### ISSUE TITLE
'Not enough CRC bytes to compute'  on opening PS2 DVD ISO file

### ISSUE THREAD

**Issue by 320x200** [clalancette/pycdlib#11]
Hello,

I hesitated opening this issue, given the fact it overlaps with #4.

I am trying to open a PS2 DVD ISO image, made with `ddrescue`, but PyCdlib fails with:
```
Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    iso.open(sys.argv[1])
  File "/usr/local/lib/python3.6/dist-packages/pycdlib/pycdlib.py", line 3706, in open
    self._open_fp(fp)
  File "/usr/local/lib/python3.6/dist-packages/pycdlib/pycdlib.py", line 2243, in _open_fp
    self._parse_udf_descriptors()
  File "/usr/local/lib/python3.6/dist-packages/pycdlib/pycdlib.py", line 1860, in _parse_udf_descriptors
    anchor_tag.parse(anchor_data, extent)
  File "/usr/local/lib/python3.6/dist-packages/pycdlib/udf.py", line 486, in parse
    raise pycdlibexception.PyCdlibInternalError('Not enough CRC bytes to compute (expected at least %d, got %d)' % (self.desc_crc_length, len(data) - 16))
pycdlib.pycdlibexception.PyCdlibInternalError: Not enough CRC bytes to compute (expected at least 2032, got 496)
```
Unless, I misundertood OP's last comments in #4, opening such ISO should be possible?

Thanks!

**Comment by clalancette** [comment]
I actually don't think this is an overlap with #4.  At the time that issue was opened, pycdlib did not yet support UDF. 

At this point, pycdlib does support UDF, and the error is coming from that code.  To move forward, I'll need a couple of things:

1.  What version of pycdlib are you using?  I just release 1.5.0 yesterday, so if you can update to at least that version, that would be helpful.
1.  Access to the ISO in question would be immensely helpful.  If there is any way for you to share the ISO with me, I'll be able to debug and fix it much faster.

**Comment by 320x200** [comment]
1. I first tried with 1.4.0, and now with 1.5.0. I have the same PyCdlibInternalError message.
2. I tried different images and I get the same error, I could try to find a way to upload one somewhere. However, would you be able to get ISO images matching their redump data? I tried this one right now http://redump.org/disc/359/ and I get the error.

**Comment by clalancette** [comment]
This is an interesting problem.  It's pointed out two bugs in pycdlib already, and the ISO itself has a problem.

Bugs:
1.  We weren't always reading enough data when looking at UDF anchors; I've now fixed this in 69405e48952d0cea79d4bf5de9362c144e732477 (though that is not yet enough to successfully parse).
1.  There's something wrong in how we look up filenames in the UDF filesystem; I'm still debugging this one.

ISO problem:
- The ISO itself does not actually conform to the UDF standard.  In particular, the end UDF anchor point (2048 bytes from the end of the ISO) is supposed to have a field specifying the location of the anchor (in 2048-byte extents) into the ISO.  In this GT4 ISO, it has some other number in there.  On the one hand this is a standards violation, but on the other it isn't a very egregious one and pycdlib should probably be more graceful.  I'm still thinking about how to fix this.

**Comment by 320x200** [comment]
Thanks Chris for looking into that!

Regarding the ISO problem, out of curiosity, I tried your latest changes on another PS2 DVD ISO, produced by another publisher, and I also have a tag location error. Not the same as with the GT4 ISO, so maybe the field has another purpose?

`Tag location 0x12f does not match actual location 0x1`

**Comment by clalancette** [comment]
The thing is, the UDF spec (Ecma-167, section 7.2.8) explicitly says:

```
Tag Location (RBP 12):
This field shall specify the number of the logical sector containing the first byte of the descriptor.
```
According to Ecma-167, section 8.1.2, logical sectors must be a multiple of 512, and in my experience are almost always 2048.  Further evidence that the sector size is 2048 comes from the fact that if I comment out that check, then I can fetch files and generally interact with the ISO normally.

Going further, I usually have 3 different pieces of software I look at to see what should happen in practice (rather than just what the spec says): the Linux kernel drivers, cdrtools, and cdrkit.

1.  Linux kernel - In this case, the UDF driver in the kernel can actually parse and mount the gt4.iso.  After some digging, though, it turns out that the reason it gets away with this is because it is ignoring the "second" anchor and only ever looking at the first one (which has the correct tag location).  If I make the Linux kernel driver skip the first anchor and look at the second, it fails for the same reason pycdlib does.
1.  cdrtools - When it creates UDF ISOs, it always puts in the correct logical sector as the tag location.
1.  cdrkit - When it creates UDF ISOs, it always puts in the correct logical sector as the tag location (there are tests in pycdlib that verify this).

There are a few things left to try here:
1.  Do some more careful reading of the Linux UDF driver.  It has some additional detection algorithms that I don't quite understand yet, so I should probably spend some more time to see if any of those shed light on what is going on here.
1.  Do some additional poking around on the ISO.  In particular, I need to see if those anchor locations are consistently off for all of the rest of the tags on the ISO.  If they are off in a particular way, that suggests that the "base" logical sector number is offset by some bit, which I'll have to find.

I'll see if I can find some time this weekend to poke at this again.  Interesting problem :).

**Comment by clalancette** [comment]
All right, I've pushed commit 9038a2bc4300f60ee944e3253693aaafd46c9386, which fixes this problem in my testing.  It turns out that just the second anchor and the File Set Terminator on gt4.iso are failing, both of which are pretty benign.  I made the code silently fix the tag location if it is wrong.  I'll leave this open a little while longer so you can give it a test; please let me know how it goes!

**Comment by clalancette** [comment]
Fantastic, glad this is working for you.
