### ISSUE TITLE
When walking an ISO need to be able to get the record type.

### ISSUE THREAD

**Issue by bifferos** [clalancette/pycdlib#28]
I expected record.is_file() to only return True if the entry is a file, but it seems to also return True if it's a link.  This makes it difficult to walk an ISO with anything other than just files in it.

Here's an ISO with a link
http://bear.alienbase.nl/mirrors/slackware/slackware64-current-iso/slackware64-current-install-dvd.iso

And here is some code I'm using to extract the contents:
```
    for path, dirs, files in iso_in.walk(rr_path="/"):
        for dirname in dirs:
            dst = ISO_EXTRACT_DIR + os.path.join(path, dirname)
            print "creating  dir:", dst
            os.mkdir(dst)
        for file in files:
            src = os.path.join(path, file)
            dst = ISO_EXTRACT_DIR + src
            print "creating file:", dst
            record = iso_in.get_record(rr_path=src)
            print repr(record)
            if record.is_file():
                iso_in.get_file_from_iso(dst, rr_path=src)
            else:
                print "record is not a file, skipping"
```

**Comment by bifferos** [comment]
Ahh.  Actually it turns out the link inside that ISO is a *dead* link.  So maybe that's why it doesn't just return the file content and throws an exception.  My comment still stands, it's just not quite as bad as I thought.

**Comment by clalancette** [comment]
Thanks for the report.  And yeah, I see what you mean.  Part of the problem here is that ISO9660 itself has no concept of symlinks, but Rock Ridge does.  So when a Rock Ridge symlink is created, typically an ISO9660 "file" is created as well.  But it's a file with no data, so the data in it cannot be fetched.

There are a few different ways I can think about fixing this:
1.  Make `is_file` only return True for real files, not symlinks, on Rock Ridge (and UDF) files.
1.  Make `is_file` take a flag asking for only files, not symlinks.  This would obviously only have an effect on Rock Ridge (and UDF) files.
1.  Make `is_file` have a flag that would be like `rock_ridge=True`; if that were the case, it wouldn't return symlinks.
1.  Make the `walk` method have a parameter to skip symlink records completely.

I'll have to think about it a bit more, since I'm not quite sure what the best thing to do here would be.

**Comment by bifferos** [comment]
I've just finished v1 of my ISO extractor, based on your code.  It's here, if you want to see it:
https://github.com/bifferos/explodeinstaller
When I encounter the exception for writing out a link, I switch to isoparser, and get the record using that. I examine the SUSP entries and one of them has the link location in it when this happens.  I don't know if it makes sense for you to do something similar?  So basically that link metadata is part of the file record somehow.  See:
https://github.com/bifferos/explodeinstaller/blob/master/explodeinstaller.py#L40
But what the heck, I'm just glad I got it working... somehow.

**Comment by clalancette** [comment]
Ah, glad you found a workaround.

For what it is worth, you can do a similar workaround using just `pycdlib` (avoiding the need to parse the ISO metadata twice).  The code below is more-or-less what it would look like:

```
import os
import sys

import pycdlib

def extract_one_iso_file(iso_in, src, dest):
    local_path = dest + src
    record = iso_in.get_record(rr_path=src)
    if record.is_file():
        if record.rock_ridge is not None and record.rock_ridge.is_symlink():
            local_dir, local_link_name = os.path.split(local_path)
            src = src.split("/")[1:]
            old_dir = os.getcwd()
            os.chdir(local_dir)
            os.symlink(record.rock_ridge.symlink_path(), local_link_name)
            os.chdir(old_dir)
        else:
            iso_in.get_file_from_iso(local_path, rr_path=src)

def walk_iso(isofs_dir):
    iso_in = pycdlib.PyCdlib()
    iso_in.open('slackware64-current-install-dvd.iso')

    iso_out = pycdlib.PyCdlib()
    iso_out.new(joliet=3)
    os.mkdir(isofs_dir)

    for path, dirs, files in iso_in.walk(rr_path='/'):
        for dirname in dirs:
            dst = isofs_dir + os.path.join(path, dirname)
            print("creating dir:", dst)
            os.mkdir(dst)
        for file in files:
            src = os.path.join(path, file)
            extract_one_iso_file(iso_in, src, isofs_dir)

walk_iso('isoextract/')
```

I'll still leave this open and come up with a better way to deal with this, but this should get keep you moving along for now.

**Comment by bifferos** [comment]
Wow, thank you so much for that.  I will definitely incorporate that change.
For some reason I didn't get that from looking at the docs at:
https://clalancette.github.io/pycdlib/example-walking-iso-filesystem.html
(but I was in a big hurry).

Should I raise a ticket for the other corner case:
https://github.com/bifferos/explodeinstaller/blob/master/explodeinstaller.py#L40
This is encountered on the file /isolinux/isolinux.boot on the same ISO.  It will be nice to remove isoparser from my project because it doesn't seem to be maintained.

**Comment by clalancette** [comment]
> Should I raise a ticket for the other corner case:
> https://github.com/bifferos/explodeinstaller/blob/master/explodeinstaller.py#L51
> This is encountered on the file /isolinux/isolinux.boot on the same ISO. It will be nice to remove isoparser from my project because it doesn't seem to be maintained.

With the code I pasted above, that actually works fine for me.

Ah!  Are you using pycdlib 1.7.0?  I didn't implement the extraction of El Torito Boot Catalog until just a month ago, so it is not in a release right now.  I'm about due for a release, so once I get 1.8.0 out the door you should be able to extract that entire ISO with just pycdlib.  Stay tuned.

**Comment by bifferos** [comment]
<head-slap moment>.  I'd actually installed your github version, I just hadn't removed the pip installed one and it was preferring that.  So I've just changed the instructions to install pycdlib from source.  Eagerly awating the 1.8.0 release and then I'll update my project.  Thank you for your help.

**Comment by clalancette** [comment]
> For some reason I didn't get that from looking at the docs at:
> https://clalancette.github.io/pycdlib/example-walking-iso-filesystem.html
> (but I was in a big hurry).

To be clear, the code I've given above is a workaround.  The reason it isn't documented (there or anywhere) is because:

1.  It is a bit fragile, and won't work in all circumstances.  In particular, it won't do the correct thing when opening a UDF ISO, which also has the concept of symlinks.
1.  It is reaching into the internals of pycdlib.  While I guarantee API compatibility for the public, documented APIs, I reserve the right to change the internals.

In any case, I will make sure to add a documented, supported symlink API that will take care of both of the above issues before I do a 1.8.0 release.

**Comment by clalancette** [comment]
All right, I've implemented `is_symlink()` for the DirectoryRecord object in 8afbab4432ef7f497118c273e6e202e589cc04a6, which makes it compatible with the `UDFFileEntry` object.  So you should be able to use that instead of my previous workaround, and I think that will work for both ISOs and UDF.  I'm going to close this out for now, but feel free to comment more or reopen if that doesn't work for you.

**Comment by bifferos** [comment]
Yes, I understand the issue you are facing.  You have a base standard created many years ago and some subsequent standards layered on top.  You want to cater for the lowest level of forensic access to an image.  However I think the vast majority of your users aren't going to be using your library that way.  They will probably just try to guess the mkisofs options used in creating the image and then want some kind of facade that presents the file system in a uniform way, just as if they'd mounted it.
So I think your library would benefit massively in terms of usability if one could request some kind of wrapper object e.g.:
`iso = pycdlib.PyCdlib()
rr = pycdlib.get_rr_facade(iso)
rr.get_file_from_iso_fp(extracted, "/some/rr/folder/path")`
Of course, that's easy for me to say, and a bunch of work for you, but I thought I'd just put that out there.  The library is perfectly useful for me as it is.

**Comment by clalancette** [comment]
Oh, I like the idea of the facade for the different extensions.  I'll put it on my TODO list to look into in the future.  Thanks!
