### ISSUE TITLE
UDF NSR03 identifer

### ISSUE THREAD

**Issue by Landcross** [clalancette/pycdlib#32]
Hi,

I'm trying to load a Blu-Ray with pycdlib, but it throws the following error:

> pycdlib.pycdlibexception.PyCdlibInvalidISO: Partition Contents Identifier not '+NSR02'

I've taken a look at what the actual value is, and it's NSR03. A quick google led me to here: https://wiki.osdev.org/UDF which says that NSR02 and NSR03 both describe the same thing: a UDF file system.

Now, I don't know anything about file systems and though they sound similar, I guess they aren't? Is it possible to add this NSR03 support?

**Comment by clalancette** [comment]
> pycdlib.pycdlibexception.PyCdlibInvalidISO: Partition Contents Identifier not '+NSR02'

Ah, right.  I added support for the NSR03 while parsing the NSR Volume structure, but I forgot to do the same for the Partition Volume Descriptor.  Commit 36140588fa453996151b36963851a93a36a4ce9b should fix that.

However, I suspect that you are going to run into other problems with a Blu-Ray anyway.  I've been working on more robust UDF/Blu-Ray support on the https://github.com/clalancette/pycdlib/tree/udf-only branch.  I've gotten fairly far there, but I still need to do some more fixes before I can call that finished and merge it into master.  I'm tracking that work in #19 and #23, so I'm going to close this for now.  Feel free to comment or re-open if you feel your issue is different.
