### ISSUE TITLE
Error adding files to iso_path with invalid filenames

### ISSUE THREAD

**Issue by willervinNTS** [clalancette/pycdlib#36]
When creating a new ISO I'm attempting to add files to iso_path and I'm getting the error: "pycdlib.pycdlibexception.PyCdlibInvalidInput: ISO9660 filenames at interchange level 1 cannot have more than 8 characters or 3 characters in the extension". 

Now I know a work around to this is creating a Joliet ISO and adding the files to it's joliet_path; however, when I try to ad El Torito to the ISO, it's not booting correctly. My question is how do I either add the files directly to the iso_path, or transfer the files from the joliet_path to the iso_path

**Comment by clalancette** [comment]
> When creating a new ISO I'm attempting to add files to iso_path and I'm getting the error: "pycdlib.pycdlibexception.PyCdlibInvalidInput: ISO9660 filenames at interchange level 1 cannot have more than 8 characters or 3 characters in the extension".

There are 3 different ISO interchange levels; level 1, 2, and 3.  Level 1 is the original, DOS-compatible version, and so only allows 8 characters for the filename and 3 characters for the extension, and only capital letters.  Level 2 isn't interesting; I'll skip it.  Level 3 also technically has some limitations (I think it is 30 characters), but in the wild there are definitely ISOs that don't conform to this and just put arbitrarily long filenames in there.  PyCdlib basically allows anything in level 3.  There is also a "interchange" level 4 which has even more relaxed restrictions, but it isn't heavily used.

> Now I know a work around to this is creating a Joliet ISO and adding the files to it's joliet_path; however, when I try to ad El Torito to the ISO, it's not booting correctly. My question is how do I either add the files directly to the iso_path, or transfer the files from the joliet_path to the iso_path

Joliet is a totally separate filesystem that lives alongside the ISO filesystem.  It is useful because of its ability to do deeper directories and Unicode, but in the context of El Torito booting, it isn't interesting.  So I'd leave out Joliet for now.

So there are a couple of things I can recommend here:
1.  Try to use interchange_level 3 instead of 1.  That will get you longer filenames (but not deeper directory structures).
1.  If you are still having problems, post the code you are using and the file you are trying to get to work here.  It is somewhat tricky to setup El Torito so that it actually works for booting; if I can see the code, I might be able to give you some pointers on things to try.

**Comment by willervinNTS** [comment]
@clalancette Thank you for the advice. Changing the interchange_level allowed me to add the files to the iso_path. Unfortunately I must still be doing something wrong with setting up El Torito. 

The only thing I'm actually doing to set up El Torito is by "iso.add_eltorito('/BOOT.CFG;1', bootcatfile='/BOOT.CAT;1')." Which I found here: https://github.com/clalancette/pycdlib/blob/master/examples/create-bootable.py and here: https://clalancette.github.io/pycdlib/example-creating-bootable-iso.html

**Comment by clalancette** [comment]
> The only thing I'm actually doing to set up El Torito is by "iso.add_eltorito('/BOOT.CFG;1', bootcatfile='/BOOT.CAT;1')." Which I found here: https://github.com/clalancette/pycdlib/blob/master/examples/create-bootable.py and here: https://clalancette.github.io/pycdlib/example-creating-bootable-iso.html

Yeah, the problem is that getting everything correct for El Torito is tricky.  Those examples are enough just to show the API usage, but not enough to make an actual bootable ISO.  In order to make it actually boot, you need basically the following:

1.  A bootfile that is *actually bootable*.  For Linux, for instance, this is generally one of the syslinux bootable files, but choosing the correct one can be tricky.
1.  Choosing the correct value for the `media_name` parameter to `add_eltorito`.  Generally `media_name` should be 'noemul' (the default), but there are circumstances where you want to use one of the other values.
1.  Choosing the correct value for the `boot_load_size` parameter to `add_eltorito`.    If using 'noemul' for the `media_name`, the `boot_load_size` should generally be 4, but sometimes other things are required.

If you can send me a pointer to the code that you are using plus the bootfile that you are trying to use, I can at least give you an idea of whether your choices are likely to work.

**Comment by willervinNTS** [comment]
Essentially what the code I'm working on is doing is taking an ESXi-6.7 ISO and altering the contents of it's BOOT.CFG file. I know that the bootfile is actually bootable because we've modified the ISO in place and its booted just fine. Since we're trying to create a completely new ISO rather than modifying one in place, I've had to copy the contents of the vanilla ISO to a directory, alter the BOOT.CFG file, and then add the contents of the directory to a brand new ISO. The basic functions I've used to do this is are: 

`iso = pycdlib.PyCdlib()`

`iso.new(interchange_level=4)`

`# This is where I edit BOOT.CFG file`

`for f in files:`
    `iso.add_file(f, iso_path=f+";1")`

`iso.add_eltorito('/BOOT.CFG;1', media_name='noemul', boot_load_size=4)`

`iso.write("ISOname.iso)`
