### ISSUE TITLE
PVD Space Size is +1 more than it should be

### ISSUE THREAD

**Issue by rlaphoenix** [clalancette/pycdlib#63]
pvd.space_size: 2063196
pvd.space_size (zero-indexed, aka -1): 2063195
pvd.space_size * 2048: 4225425408

The disc:
![image](https://user-images.githubusercontent.com/17136956/115024583-32e56e80-9eb8-11eb-98f0-005135e7531d.png)

Win Size: 4225423360
Win Size / 2048: 2063195
Win Size (zero-indexed, aka -1): 2063194

Is it +1'ing somewhere by mistake? This value is definitely incorrect as I tried to take the pvd.space_size value, as sectors, and seek to it with failure, but -1 the value, seek to it, no issues.

I will say this is tested on my [win32-test branch](https://github.com/rlaPHOENiX/pycdlib/tree/win32-test) of my light fork, just some patches to work with Windows (which I have made pull requests for).

**Comment by clalancette** [comment]
There's always the possibility of a bug.

That being said, there are extensive tests of the PVD size, so I'm fairly confident that it acts like I expect.  Maybe this particular DVD doesn't match this expectation, however.  It's worthwhile printing out what pycdlib thinks the PVD size is and compare it to what some other tools print out.

The best would be if you could provide me an example ISO file that has this problem, but I don't know if that is possible.

**Comment by clalancette** [comment]
According to offset 0x50 - 0x53 in the PVD, it does indeed look like the number of extents should be 2063196 (0x001f7b5c).  That should give you a total disc size, in bytes, of 4225425408 (which are all of the initial numbers you put before).  That's 2048 (1 extent) larger than the actual number of bytes on the disc.

The only thing I can say is that there are often bugs in CD-creation programs (this wouldn't be the first, and there are quite a number of workarounds in pycdlib so we can accept these).  It often doesn't matter because the PVD space size is really just a hint; what really matters is that the file sizes are correct.  Further, on ISOs that have both ISO9660 structures and UDF (UDF "bridge" format), the ISO9660 stuff is often ignored.  That's my guess on what is going on here.

Other than noticing the discrepancy, are you having any trouble with it?

**Comment by rlaPHOENiX** [comment]
Yeah, since the extent is 1 too much, all the code that uses it (like the UDF anchor locations) would be wrong. And if I try to use that to know how much of the disc to read, I'd end up trying to read 1 sector more than possible.

I'm just worried that if this pvd.space_size is an incorrect value (regardless if it's over by 1, under by 1, or an insanely wrong value) if that is a danger to the rest of the code. Would that cause problems?

For me, I could just check and see if the device can seek and read at the address and if not assume finished even if pvd.space_size says to continue on. But as I said I'm just worried about the rest of the code. It seems to be used often and in important ways.

**Comment by clalancette** [comment]
So it actually is a problem, and in point of fact a similar problem is one of the reasons that pycdlib goes and tries to find the "true" end of the disc in the first place.  See https://github.com/clalancette/pycdlib/blob/master/pycdlib/pycdlib.py#L1194-L1205 for the code; essentially we'll internally "fix-up" the PVD size in the case where we detect it is wrong.  This came about because I had an ISO where the final directory record actually extended beyond the bounds of the disc; the PVD size was too short, but all of the data was actually present on disc.  So internally extending the PVD size worked fine.

You seem to have the opposite problem, where the PVD describes a disc that is larger than the number of bytes.  If the PVD was calculated wrong when the disc was made, then from a data integrity perspective, this is OK.  All of the data is there, the PVD is just reported wrong.  If the PVD is actually correct, though, you'll have data loss and you are right that the rest of pycdlib is going to have trouble.

It may be worth while to try and put code in so that pycdlib can detect the situation you have, adjust the PVD size internally, and hope for the best.  If there is data loss, we'll still probably fail soon after, but if it is just calculated wrong, everything else should work OK.

**Comment by rlaPHOENiX** [comment]
So to clarify you are saying if the space_size extends beyond the physical disc size, the pycdlib code won't really care and will operate fine as if it was the correct space_size?

If so, that's good. I will say that the space_size doesn't technically exceed the disc size, but it does exceed what Windows Raw Device is providing access to. (5 sectors at 2048 bytes less than the disc size actually is)

**Comment by rlaphoenix** [comment]
I cannot remember what disc I used for this specific issue, but I can say it seems like this issue essentially boiled down to using Windows Raw Devices being whack about the less sectors thing.

This was fixed in the latest merge from Pull request #64 and #65 so this shouldn't be an issue anymore. It essentially boiled down to needing to call `win32file.DeviceIoControl(self.dvdcss.handle, winioctlcon.FSCTL_ALLOW_EXTENDED_DASD_IO, None, None)` after the handle is created, and before any other win32 call that would revolve around file sizes or sectors.
